Fix syntax error in requirementslib vendor
Compiling this file raised a SyntaxError:

    ***   File "/gnu/store/62ms8p25ilrw7vrz5fn8fjf4pds10b02-pipenv-2022.11.11/lib/python3.9/site-packages/pipenv/vendor/requirementslib/models/metadata.py", line 17
        from pipenv.patched.pip._vendor.distlib.metadata import import Metadata
                                                                ^
    SyntaxError: invalid syntax

Found through `python -m compileall /pipenv/source/` when trying to add pipenv to
[Guix](https://guix.gnu.org/).

Also include fix for root cause: wrong replacement in vendoring task.